[package]
org = "ballerina"
name = "websubhub"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../websubhub-native/build/libs/websubhub-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "web-sub"
version = "@project.version@"
