[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "mime"
version = "@stdlib.mime.version@"

[[dependency]]
org = "ballerina"
name = "http"
version = "@stdlib.http.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "url"
version = "@stdlib.url.version@"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "@stdlib.uuid.version@"
