---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "config-config-map"
data:
  Config.toml: "[kafkaHub.config]\n# Flag to check whether to enable/disable security\n\
    SECURITY_ON = false\n\n# Server ID is is used to uniquely identify each server\
    \ \n# Each server must have a unique ID\nSERVER_ID = \"server-1\"\n\n# IP and\
    \ Port of the Kafka bootstrap node\nKAFKA_BOOTSTRAP_NODE = \"172.17.0.12:9092\"\
    \n\n# Kafka topic which will get notified for websub topic registration/deregistration\n\
    # All the hubs must be pointed to the same Kafka topic to notify websub topic\
    \ registration/deregistration\nREGISTERED_WEBSUB_TOPICS_TOPIC = \"registered-websub-topics\"\
    \n\n# Kafka topic which stores consolidated websub topics for the hub\nCONSOLIDATED_WEBSUB_TOPICS_TOPIC\
    \ = \"consolidated-websub-topics\"\n\n# Kafka topic which will get notified for\
    \ websub subscription/unsubscription\n# All the hubs must be pointed to the same\
    \ Kafka topic to notify websub subscription/unsubscription\nWEBSUB_SUBSCRIBERS_TOPIC\
    \ = \"registered-websub-subscribers\"\n\n# Kafka topic which is stores consolidated\
    \ websub subscribers for this server\nCONSOLIDATED_WEBSUB_SUBSCRIBERS_TOPIC =\
    \ \"consolidated-websub-subscribers\"\n\n# The interval in which Kafka consumers\
    \ wait for new messages\nPOLLING_INTERVAL = 10.0\n\n# The period in which Kafka\
    \ close method waits to complete\nGRACEFUL_CLOSE_PERIOD = 5.0\n\n# The port that\
    \ is used to start the hub\nHUB_PORT = 9000\n\n# The period between retry requests\n\
    MESSAGE_DELIVERY_RETRY_INTERVAL = 3.0\n\n# The maximum retry count\nMESSAGE_DELIVERY_COUNT\
    \ = 3\n\n# The message delivery timeout\nMESSAGE_DELIVERY_TIMEOUT = 10.0\n\n#\
    \ The base URL of IDP\nMOSIP_AUTH_BASE_URL = \"https://host/\"\n\n# The token\
    \ validation URL of IDP\nMOSIP_AUTH_VALIDATE_TOKEN_URL = \"https://host/oauth2/token\"\
    \n"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "kafkaHub"
  name: "kafkahub-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kafkaHub"
  template:
    metadata:
      labels:
        app: "kafkaHub"
    spec:
      containers:
      - env:
        - name: "BAL_CONFIG_FILES"
          value: "/home/ballerina/conf/Config.toml:"
        image: "websubazurehub.azurecr.io/kafkahub:v2"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "kafkahub-deployment"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/home/ballerina/conf/"
          name: "config-config-map-volume"
          readOnly: false
      nodeSelector: {}
      volumes:
      - configMap:
          name: "config-config-map"
        name: "config-config-map-volume"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "kafkaHub"
  name: "kafkahub-hpa"
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "kafkahub-deployment"
  targetCPUUtilizationPercentage: 50
