---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "config-config-map"
data:
  Config.toml: "[kafkaHub.config]\n# Flag to check whether to enable/disable security\n\
    SECURITY_ON = false\n\n# Server ID is is used to uniquely identify each server\
    \ \n# Each server must have a unique ID\nSERVER_ID = \"server-1\"\n\n# IP and\
    \ Port of the Kafka bootstrap node\nKAFKA_BOOTSTRAP_NODE = \"172.17.0.12:9092\"\
    \n\n# Kafka topic which will get notified for websub topic registration/deregistration\n\
    # All the hubs must be pointed to the same Kafka topic to notify websub topic\
    \ registration/deregistration\nREGISTERED_WEBSUB_TOPICS_TOPIC = \"registered-websub-topics\"\
    \n\n# Kafka topic which stores consolidated websub topics for the hub\nCONSOLIDATED_WEBSUB_TOPICS_TOPIC\
    \ = \"consolidated-websub-topics\"\n\n# Kafka topic which will get notified for\
    \ websub subscription/unsubscription\n# All the hubs must be pointed to the same\
    \ Kafka topic to notify websub subscription/unsubscription\nWEBSUB_SUBSCRIBERS_TOPIC\
    \ = \"registered-websub-subscribers\"\n\n# Kafka topic which is stores consolidated\
    \ websub subscribers for this server\nCONSOLIDATED_WEBSUB_SUBSCRIBERS_TOPIC =\
    \ \"consolidated-websub-subscribers\"\n\n# The interval in which Kafka consumers\
    \ wait for new messages\nPOLLING_INTERVAL = 10.0\n\n# The period in which Kafka\
    \ close method waits to complete\nGRACEFUL_CLOSE_PERIOD = 5.0\n\n# The port that\
    \ is used to start the hub\nHUB_PORT = 9000\n\n# The period between retry requests\n\
    MESSAGE_DELIVERY_RETRY_INTERVAL = 3.0\n\n# The maximum retry count\nMESSAGE_DELIVERY_COUNT\
    \ = 3\n\n# The message delivery timeout\nMESSAGE_DELIVERY_TIMEOUT = 10.0\n\n#\
    \ The base URL of IDP\nMOSIP_AUTH_BASE_URL = \"https://host/\"\n\n# The token\
    \ validation URL of IDP\nMOSIP_AUTH_VALIDATE_TOKEN_URL = \"https://host/oauth2/token\"\
    \n"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "kafkahub-server-key"
data:
  server.key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC02iLyGGYYvLg6\n\
    +PEgpupiyOWf8I1QY0qUi+WwDp1XSeMYl8/0AFWXvfOebXFcJGrMVAlZDLrEEjhK\nUb+ao+wSLG7jPqmgV9vpHyXNjXk+DPqjQ2LtVL1gEz/+/Rc3BGo8CJi5g43W47dj\n\
    cD7SXrY9NizLMUw1cI7Vb6Fqz45rexZO9nNnYNxOJkxgCONWSXwsujhbhNv9lexD\nG+cGdTwWSKze9mcjagxKjTuQmrxI2xBm822i61ZGnbfw2esHtkbIuBt/roGwetB/\n\
    HRF1xrhz1C8tteV5JpFIERKiR2svnNGIdGxxvaOEF/8mpgik5o+xEJspnXiG+ERA\nfiRsB+1VAgMBAAECggEBAKiJSFu4ZRzUchNy/rLhGjho46TDNc4eWdhI7wm89N/t\n\
    mVbH0yGeViWM/UU81JF71pMIFZYJCNvD5vVLbXWdIVhmVAgt00H73pJHVqFSIBS1\nX7VaDQ0DFWA9UDw+e63nzWCY2kq30CzcFYDzj3fYj5hHrkLFdDGw7Ur2NsUlG6II\n\
    hUpuTgbOVUPBimwWTK5mnXFsJ4hwiR4JSCEDhdFOkaJk9e8KAA6AKU1E/QYtsViG\nQMfVNcN68XaQd7f37M2rx+rBCHgIb2X8CD9x77UE9rkZHhADqBtepM4Z904VPla2\n\
    3XOyXUKBdsUhUbzmUL02Di2Bed1aiCoEsoglw/diKQECgYEA8PdW45c0Zd0mcWaf\nBtsjNiQnD/LL1qNkJKAVFpOVIQ8Z+xJjkrY20kANC2WLqSZyDQubDAoZagazRXtn\n\
    MimsR4iR2rrjjsq+eaO6hR+oOCOGGwq+LeFyrcoMWDVNmWMEbRIbBTEXga+Yz0XO\nXmm1phNoVVqH5CDYr6GUVG5eJKECgYEAwCKq+DBLdrWUYY1xPD2Aem3FYMaU4enw\n\
    1XwYnekv2glxggGOXYQgoAR9HDpWraMg78gRZLRJ/hU8orG9++KJ1dfmQiOct6r2\nhKpVakeQHuzJr2YAYGb52KhvQcgkQyQnTSeJ8mT6oVQqUcvM2iB4Ye0QrBb6Qrfo\n\
    Lnvabb4TWDUCgYEAwfGRkaTFm6cfpe4+2LnP4We/uOpmfd8MXx4pWv517SHGe3oV\ngqP+A8NhvGaCviYfbbiFlm8afWffKnFkYc+AxiJ5ol8BgJBWNnk9SqBsOKL+8Qz4\n\
    fN0T/CS/Qs/EIUy85zzHWqpkjRDUIR/CNeNHPOAp/WjcLxTw0otuY3Zhd4ECgYBp\n4nEgR9U+vYDhZgaScT5duiL9W1LvUXKE5FfYporVeUDRqbPge5FTPkYIiWn9VRow\n\
    qqxTODxSxzdcXeHab5UQgWQG7QNQAOrMX+akpH2bXVkkzWzFs9pa+TAfK4I4cjMq\nhPCz4cxxniWYYF0rlJtjNDds71jJ7foJq/3LXuXgRQKBgFfZ3kxfxg0bGDK9aWAq\n\
    az14d3Ok2ZNnCzySYM/p8Ej+wTPjnDd7CLax8AT3oPf9po2uCwnmi15QtYebg0Dn\nRlSVps/2srXwUAsr9tGZcyp+pRQfRUk8LoBog9U+q37gI8JtyWdqrOJuZQKpxxly\n\
    h/H9HawGZOogkygzAhNYFn6Q\n-----END PRIVATE KEY-----\n"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "kafkahub-server-crt"
data:
  server.crt: "-----BEGIN CERTIFICATE-----\nMIID0TCCArmgAwIBAgIUEggNaNPp0RJaDsFP/9ZqVaPEdLEwDQYJKoZIhvcNAQEL\n\
    BQAweDELMAkGA1UEBhMCU0wxEDAOBgNVBAgMB1dFU1RFUk4xEDAOBgNVBAcMB0NP\nTE9NQk8xGzAZBgNVBAoMEldTTzIgTGFua2EgUFZUIExURDEUMBIGA1UECwwLRU5H\n\
    SU5FRVJJTkcxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0yMTA2MTAwNDQ4MzVaFw0y\nMjA2MTAwNDQ4MzVaMHgxCzAJBgNVBAYTAlNMMRAwDgYDVQQIDAdXRVNURVJOMRAw\n\
    DgYDVQQHDAdDT0xPTUJPMRswGQYDVQQKDBJXU08yIExhbmthIFBWVCBMVEQxFDAS\nBgNVBAsMC0VOR0lORUVSSU5HMRIwEAYDVQQDDAlsb2NhbGhvc3QwggEiMA0GCSqG\n\
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC02iLyGGYYvLg6+PEgpupiyOWf8I1QY0qU\ni+WwDp1XSeMYl8/0AFWXvfOebXFcJGrMVAlZDLrEEjhKUb+ao+wSLG7jPqmgV9vp\n\
    HyXNjXk+DPqjQ2LtVL1gEz/+/Rc3BGo8CJi5g43W47djcD7SXrY9NizLMUw1cI7V\nb6Fqz45rexZO9nNnYNxOJkxgCONWSXwsujhbhNv9lexDG+cGdTwWSKze9mcjagxK\n\
    jTuQmrxI2xBm822i61ZGnbfw2esHtkbIuBt/roGwetB/HRF1xrhz1C8tteV5JpFI\nERKiR2svnNGIdGxxvaOEF/8mpgik5o+xEJspnXiG+ERAfiRsB+1VAgMBAAGjUzBR\n\
    MB0GA1UdDgQWBBThDqTbrO4NqtU34kVQs22zGPtzejAfBgNVHSMEGDAWgBThDqTb\nrO4NqtU34kVQs22zGPtzejAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA\n\
    A4IBAQBCOiKtJ9FBzcWwAvy680uojEVf8V+fICZVeURy7dPin+mYxBoJirAraEcB\nE9Kw0yLWux4+xOsr53rTv/e0aT4H9b/Lubr5hGgJZhF/DyCdhrirsjZKCsQ8JfWh\n\
    wycEXSFIrm+1cqyDh2urYgvQtjfPv1njmcwq4LYX+Q6HnnlX7t2LztpLeZ3ahZpY\nNuhHeo/eRndhBvv1/5a8nmLnFRvz7su7orCai3KpInRCssZeRVZI76i6Nw3PhWBk\n\
    vr8yDaWBwMkx1nCKCoNRRbykR50HlUXwOwy/7SvQOdYwmpL6yT54uCNIOxmsovGW\nOmQU+LITZzuGdISXoTIagcbEtQbf\n\
    -----END CERTIFICATE-----\n"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "kafkaHub"
  name: "kafkahub-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kafkaHub"
  template:
    metadata:
      labels:
        app: "kafkaHub"
    spec:
      containers:
      - env:
        - name: "BAL_CONFIG_FILES"
          value: "/home/ballerina/conf/Config.toml:"
        image: "websubazurehub.azurecr.io/kafkahub:v1"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "kafkahub-deployment"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/home/ballerina/conf/"
          name: "config-config-map-volume"
          readOnly: false
        - mountPath: "/home/ballerina/resorces/server.key"
          name: "kafkahub-server-key-volume"
          readOnly: true
          subPath: "server.key"
        - mountPath: "/home/ballerina/resorces/server.crt"
          name: "kafkahub-server-crt-volume"
          readOnly: true
          subPath: "server.crt"
      nodeSelector: {}
      volumes:
      - configMap:
          name: "config-config-map"
        name: "config-config-map-volume"
      - configMap:
          name: "kafkahub-server-key"
        name: "kafkahub-server-key-volume"
      - configMap:
          name: "kafkahub-server-crt"
        name: "kafkahub-server-crt-volume"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "kafkaHub"
  name: "kafkahub-hpa"
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "kafkahub-deployment"
  targetCPUUtilizationPercentage: 50
