---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "kafkaHub"
  name: "kafkaHub-svc"
spec:
  ports:
    - name: "port-1-in-mem"
      port: 9000
      protocol: "TCP"
      targetPort: 9000
  selector:
    app: "kafkaHub"
  type: "ClusterIP"
