[package]
org = "example"
name = "kafkaHub"
version = "0.1.0"
distribution = "2201.10.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "websubhub"
version = "1.13.1"
repository = "local"
