[consolidatorService.config]
# IP and Port of the Kafka bootstrap node
KAFKA_BOOTSTRAP_NODE = {{ .Values.deployment.config.kafka.bootstrap_node | quote }}

# Kafka topic which stores websub-events for this server
WEBSUB_EVENTS_TOPIC = {{ .Values.deployment.config.kafka.websub_events_topic | quote }}

# Kafka topic which stores the current snapshot for the websub-events
WEBSUB_EVENTS_SNAPSHOT_TOPIC = {{ .Values.deployment.config.kafka.websub_events_snapshot_topic | quote }}

# The interval in which Kafka consumers wait for new messages
POLLING_INTERVAL = 10.0

# The period in which Kafka close method waits to complete
GRACEFUL_CLOSE_PERIOD = 5.0

# The port that is used to start the HTTP endpoint for consolidator
CONSOLIDATOR_HTTP_ENDPOINT_PORT = {{ .Values.deployment.config.port }}

# The MTLS configurations related to Kafka connection
[kafkaHub.config.KAFKA_MTLS_CONFIG]
cert.path = "/home/ballerina/resources/brokercerts/{{ .Values.deployment.config.kafka.truststore_name }}"
cert.password = {{ .Values.deployment.config.kafka.truststore_password | quote }}
key.keyStore.path = "/home/ballerina/resources/brokercerts/{{ .Values.deployment.config.kafka.keystore_name }}"
key.keyStore.password = {{ .Values.deployment.config.kafka.keystore_password | quote }}
