[package]
org = "ballerina"
name = "websubhub"
version = "1.3.0"
authors = ["Ballerina"]
keywords = ["websub", "hub", "publisher", "service", "listener", "client"]
repository = "https://github.com/ballerina-platform/module-ballerina-websubhub"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.1.0"

[[platform.java11.dependency]]
path = "../native/build/libs/websubhub-native-1.3.0-SNAPSHOT.jar"
