[container.image]
repository="ballerina"
name="consolidator"
tag="v1"

[[container.copy.files]]
sourceFile="./Config.toml"
target="/home/ballerina/Config.toml"

[[cloud.config.files]]
file="./Config.toml"
