[consolidatorService.config]
# Azure Event Hub namespace connection
SYSTEM_INFO_NAMESPACE = "localhost:9092"

# Path to the file containing the system-info EventHub connection-string
SYSTEM_INFO_NAMESPACE_CONNECTION_STRING_FILE = "./resources/system-info"

# Partitions in `system-info` EventHub which will get notified for websub topic registration/deregistration
REGISTERED_WEBSUB_TOPICS_PARTITION = 0

# Partitions in `system-info` EventHub which stores consolidated websub topics for the hub
CONSOLIDATED_WEBSUB_TOPICS_PARTITION = 1

# Partitions in `system-info` EventHub which will get notified for websub subscription/unsubscription
WEBSUB_SUBSCRIBERS_PARTITION = 2

# Partitions in `system-info` EventHub which is stores consolidated websub subscribers for this server
CONSOLIDATED_WEBSUB_SUBSCRIBERS_PARTITION = 3

# Partitions in `system-info` EventHub which will get notified for system events
SYSTEM_EVENTS_PARTITION = 4

# Partitions in `system-info` EventHub which stores vacant event-hub mappings
VACANT_EVENT_HUB_MAPPINGS_PARTITION = 5

# Partitions in `system-info` EventHub which is stores consolidated vacant event-hub mappings
CONSOLIDATED_VACANT_EVENT_HUB_MAPPINGS_PARTITION = 6

# Partitions in `system-info` EventHub which stores vacant event-hub consumer-group mappings
VACANT_EVENT_HUB_CONSUMER_GROUP_MAPPINGS_PARTITION = 7

# Partitions in `system-info` EventHub which is stores consolidated vacant event-hub consumer-group mappings
CONSOLIDATED_VACANT_EVENT_HUB_CONSUMER_GROUP__MAPPINGS_PARTITION = 8

# The interval in which Kafka consumers wait for new messages
POLLING_INTERVAL = 10.0

# The period in which Kafka close method waits to complete
GRACEFUL_CLOSE_PERIOD = 5.0
