[consolidatorService.config]
# IP and Port of the Kafka bootstrap node
KAFKA_BOOTSTRAP_NODE = "localhost:9094"

# Kafka topic which stores websub-events for this server
WEBSUB_EVENTS_TOPIC = "websub-events"

# Kafka topic which stores the current snapshot for the websub-events
WEBSUB_EVENTS_SNAPSHOT_TOPIC = "websub-events-snapshot"

# The interval in which Kafka consumers wait for new messages
POLLING_INTERVAL = 10.0

# The period in which Kafka close method waits to complete
GRACEFUL_CLOSE_PERIOD = 5.0

# The port that is used to start the HTTP endpoint for consolidator
CONSOLIDATOR_HTTP_ENDPOINT_PORT = 10001

# The MTLS configurations related to Kafka connection
[kafkaHub.config.KAFKA_MTLS_CONFIG.cert]
path = "./resources/brokercerts/client-truststore.jks"
password = "password"

[kafkaHub.config.KAFKA_MTLS_CONFIG.key.keystore]
path = "./resources/brokercerts/client-keystore.jks"
password = "password"
