resources:
  - sampleSubscriber.yaml
  - service.yaml

patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: samplesubscribe-deployment
