[container.image]
repository="ballerina"
name="loadbalancersvc"
tag="v1"

[[container.copy.files]]
sourceFile="./resources"
target="/home/ballerina/resources"

[[cloud.config.files]]
file="./Config.toml"
